### ISSUE TITLE
Sentence not correct : You have two options for executing the Relational Database Backend booster

### ISSUE THREAD

**Issue by cmoulliard** [fabric8-launcher/appdev-documentation#784]
This sentence is not correct at all. Launcher is a project builder generating either a zip file or git project which is next used to automated the build and deployment. In both cases, the oc client will be used.

"2.3.1. Building and Deploying the Relational Database Backend Booster to OpenShift Online
You have two options for executing the Relational Database Backend booster on OpenShift Online:
Using Fabric8 Launcher
Using the oc CLI client
There is no functional difference between these methods, choose the one you prefer."

**Comment by rhoads-zach** [comment]
@cmoulliard do you just disagree with saying "Using the oc CLI client" since the oc client is used behind the scenes in the "Using Fabric8 Launcher"? Or is there a larger issue that you have?

It is true that the oc client is used in the "Using Fabric8 Launcher" approach, but the user never has to use the oc client when deploying the booster if they use the "Using Fabric8 Launcher" approach. They may have to use it when interacting with the booster later, but the don't have to use it at all during deployment.
